GET http://localhost:3005/users

###

GET http://localhost:3005/recipes/2

###

POST http://localhost:3005/users
Content-Type: application/json

{
    "username": "Milenaaa",
    "password": "6789abcd",
    "email": "nesto00@gmail.com"
}

###

DELETE http://localhost:3005/recipes/2